# Generated by Django 3.2.5 on 2021-07-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('optiona', models.CharField(max_length=200)),
                ('optionb', models.CharField(max_length=200)),
                ('optionc', models.CharField(max_length=200)),
                ('optiond', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=200)),
            ],
        ),
    ]
