# Generated by Django 3.2.5 on 2021-07-17 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_scoremodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoremodel',
            name='lifeline',
            field=models.CharField(default='0', max_length=2),
        ),
    ]
