# Generated by Django 3.2.5 on 2021-07-15 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserloginDetails',
        ),
    ]
